### ISSUE TITLE
The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions.

### ISSUE THREAD

**Issue by wilsonlichina** [aws-samples/aws-waf-bot-control-api-protection-with-captcha#4]
I'm getting the error in cloud9 as following:

SpaCrossDomainWafStack: deploying... [1/1]
SpaCrossDomainWafStack: creating CloudFormation changeset...
5:55:29 PM | CREATE_FAILED        | AWS::Lambda::Function                           | CustomS3AutoDelete...derHandler9D90184F
Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recomme
nd you use a supported runtime while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: b36fae4e-748e-43f5-9251-4310e1b2992
6)" (RequestToken: 73f4e355-3bc7-84d5-9fc2-18f99784bfc3, HandlerErrorCode: InvalidRequest)

 ❌  SpaCrossDomainWafStack failed: Error: The stack named SpaCrossDomainWafStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use a supported runtime while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: b36fae4e-748e-43f5-9251-4310e1b29926)" (RequestToken: 73f4e355-3bc7-84d5-9fc2-18f99784bfc3, HandlerErrorCode: InvalidRequest)
    at FullCloudFormationDeployment.monitorDeployment (/home/ec2-user/.nvm/versions/node/v22.8.0/lib/node_modules/aws-cdk/lib/index.js:458:10567)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.deployStack2 [as deployStack] (/home/ec2-user/.nvm/versions/node/v22.8.0/lib/node_modules/aws-cdk/lib/index.js:461:200334)
    at async /home/ec2-user/.nvm/versions/node/v22.8.0/lib/node_modules/aws-cdk/lib/index.js:461:181756

 ❌ Deployment failed: Error: The stack named SpaCrossDomainWafStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use a supported runtime while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: b36fae4e-748e-43f5-9251-4310e1b29926)" (RequestToken: 73f4e355-3bc7-84d5-9fc2-18f99784bfc3, HandlerErrorCode: InvalidRequest)
    at FullCloudFormationDeployment.monitorDeployment (/home/ec2-user/.nvm/versions/node/v22.8.0/lib/node_modules/aws-cdk/lib/index.js:458:10567)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.deployStack2 [as deployStack] (/home/ec2-user/.nvm/versions/node/v22.8.0/lib/node_modules/aws-cdk/lib/index.js:461:200334)
    at async /home/ec2-user/.nvm/versions/node/v22.8.0/lib/node_modules/aws-cdk/lib/index.js:461:181756

The stack named SpaCrossDomainWafStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use a supported runtime while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: b36fae4e-748e-43f5-9251-4310e1b29926)" (RequestToken: 73f4e355-3bc7-84d5-9fc2-18f99784bfc3, HandlerErrorCode: InvalidRequest)
admin:~/environment/aws-waf-bot

**Comment by achrafsouk** [comment]
please update your cdk, pull the latest changes and try again !
